import { Activity, ArrowRight, BookOpen, Code2, Database, FilePlus2, FlaskConical, Target, UploadCloud } from 'lucide-react';
import type { Analysis, ExamPrep } from './types';

type Props = { latest?: Analysis; exam?: ExamPrep; onPage: (page: 'Proof Sprints' | 'Exam Prep' | 'Skill Map') => void; onExam: (kind: 'syllabus' | 'past paper') => void };

export default function Overview({ latest, exam, onPage, onExam }: Props) {
  const testing = latest?.findings.find(item => item.skill === 'Testing');
  const sprint = testing?.level === 'strong' ? 'Deepen your API test proof' : 'Make your API testable';
  return <>
    <div className="welcome-strip"><strong>Welcome back!</strong><span>Keep building. Small steps create big opportunities.</span><button onClick={() => onPage('Proof Sprints')}>Your next task <ArrowRight size={16} /></button></div>
    <div className="hero new-hero"><div className="mountains" aria-hidden="true"><span /><span /><span /><i /></div><div className="hero-copy"><h1>Build skills.<br /><em>Prove progress.</em></h1><p>Turn your learning into real evidence. Combine focused practice<br className="desktop-break" /> with hands-on work to build a stronger backend portfolio.</p><div className="hero-benefits"><span><BookOpen size={21} /> Learn with purpose</span><span><Target size={21} /> Practice in context</span><span><Activity size={21} /> Show what you can do</span></div></div></div>
    <div className="overview-grid new-overview-grid">
      <section className="card sprint-card new-sprint-card"><div className="card-heading"><span className="tile violet"><Target size={23} /></span><strong>Your next proof sprint</strong><span className="duration">2–3 hours</span></div><h2>{sprint}</h2><p>Build and test a simple REST API with automated tests.</p><div className="sprint-progress"><i /><span>Ready to start</span></div><div className="sprint-steps"><div><b>1</b><span><strong>Select endpoints</strong><small>Choose key API endpoints to test.</small></span></div><div><b>2</b><span><strong>Write integration tests</strong><small>Use a test runner to check real behavior.</small></span></div><div><b>3</b><span><strong>Share your pull request</strong><small>Push your tests to a public repository.</small></span></div></div><div className="card-actions"><button className="primary" onClick={() => onPage('Proof Sprints')}>Continue sprint <ArrowRight size={16} /></button><button className="link-button" onClick={() => onPage('Proof Sprints')}>View sprint details <ArrowRight size={14} /></button></div></section>
      <section className="card exam-teaser"><div className="card-heading"><span className="tile lavender"><BookOpen size={23} /></span><strong>Exam Prep</strong><span className="status strong">New</span></div><h2>Turn your syllabus into a focused study plan.</h2><p>Upload your syllabus and past papers to see priority topics, practice questions, and a study PDF.</p><div className="exam-teaser-actions"><button className="exam-drop" onClick={() => onExam('syllabus')}><UploadCloud size={29} /><strong>Upload syllabus</strong><small>Start with a readable file</small></button><button className="secondary" onClick={() => onExam('past paper')}><FilePlus2 size={17} /> Add past papers</button></div><small className="exam-note">Text-based PDF, TXT or Markdown · Priorities are study suggestions</small>{exam && <button className="link-button exam-view" onClick={() => onPage('Exam Prep')}>View your study plan <ArrowRight size={14} /></button>}</section>
    </div>
    <section className="card skill-evidence"><div className="card-heading"><span className="tile lavender"><Database size={19} /></span><strong>Skill evidence</strong><small>Signals from your public work</small><button className="link-button" onClick={() => onPage('Skill Map')}>View all skills <ArrowRight size={14} /></button></div><div className="skill-evidence-row">{(['API design','Databases','Testing'] as const).map((skill, i) => { const finding = latest?.findings.find(item => item.skill === skill); const Icon = i === 0 ? Code2 : i === 1 ? Database : FlaskConical; return <div key={skill}><span className="tile lavender"><Icon size={20} /></span><strong>{skill}</strong><small>{finding ? `${finding.level} signal` : 'Add evidence'}</small><span className={`evidence-line ${finding?.level || 'none'}`}><i /></span></div>; })}</div></section>
  </>;
}
